# Generated by Django 2.1.7 on 2021-07-14 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rebpbsinfoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='netmeterinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile'),
        ),
    ]
