# Generated by Django 2.1.7 on 2021-07-14 22:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rebpbsinfoapp', '0002_auto_20210714_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='netmeterinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
