# Generated by Django 2.1.7 on 2021-07-16 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rebpbsinfoapp', '0003_auto_20210714_2201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='netmeterinfo',
            old_name='pbs_code',
            new_name='office_code',
        ),
        migrations.RemoveField(
            model_name='netmeterinfo',
            name='user',
        ),
    ]
