# Generated by Django 2.2 on 2021-10-05 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_office_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='office_code',
            field=models.CharField(db_index=True, max_length=3, null=True, unique=True),
        ),
    ]
