# Generated by Django 2.2 on 2021-10-05 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20211005_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='office_code',
            field=models.CharField(blank=True, db_index=True, max_length=3, null=True, unique=True),
        ),
    ]
