# Generated by Django 2.2 on 2021-10-13 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20211005_0152'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_role',
            field=models.CharField(choices=[('admin', 'Admin'), ('mod', 'Moderator'), ('user', 'User')], default='user', max_length=5),
        ),
    ]
