# Generated by Django 2.1.7 on 2021-08-03 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SolarPanelInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_month_solar_panel_consumer_nos', models.IntegerField(blank=True, null=True)),
                ('last_month_solar_panel_capacity', models.IntegerField(blank=True, null=True)),
                ('month', models.CharField(blank=True, max_length=50, null=True)),
                ('year', models.CharField(blank=True, max_length=50, null=True)),
                ('fy', models.CharField(blank=True, max_length=50, null=True)),
                ('pbs_code', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
